from __future__ import annotations

import copy
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any
from importlib import resources


TEMPLATE_FILENAME = "osc_advanced_sequence_template.json"
TEMPLATE_PACKAGE = "fzastro_ai.resources.nina_templates"
TEMPLATE_PATH = (
    Path(__file__).resolve().parents[1]
    / "resources"
    / "nina_templates"
    / TEMPLATE_FILENAME
)


def resolve_osc_template_path(path: str | Path | None = None) -> Path:
    """Resolve the bundled N.I.N.A. Advanced Sequencer template.

    PyInstaller one-file builds extract data files under ``sys._MEIPASS``.
    Developer runs load the same file from the source tree.  Keeping both
    paths here makes the imaging planner work in source and in the EXE.
    """

    if path:
        explicit_path = Path(path)
        if explicit_path.is_file():
            return explicit_path
        raise FileNotFoundError(
            f"N.I.N.A. sequence template not found: {explicit_path}"
        )

    candidates = [
        TEMPLATE_PATH,
    ]

    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        candidates.append(
            Path(meipass)
            / "fzastro_ai"
            / "resources"
            / "nina_templates"
            / TEMPLATE_FILENAME
        )

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    try:
        resource_path = resources.files(TEMPLATE_PACKAGE).joinpath(TEMPLATE_FILENAME)
        if resource_path.is_file():
            return Path(str(resource_path))
    except Exception:
        pass

    searched = "; ".join(str(candidate) for candidate in candidates)
    raise FileNotFoundError(
        "N.I.N.A. sequence template is missing from the application bundle. "
        "Rebuild the EXE after adding fzastro_ai/resources/nina_templates to PyInstaller data. "
        f"Searched: {searched}"
    )


@dataclass(frozen=True)
class NinaSequencePlan:
    target_name: str
    ra: str
    dec: str
    start_iso: str
    end_iso: str
    exposure_seconds: int
    gain: int
    frames: int
    min_altitude_deg: float = 30.0
    note: str = (
        "Generated by FZAstro AI as a review-only N.I.N.A. Advanced Sequencer plan."
    )


def load_osc_template(path: str | Path | None = None) -> dict[str, Any]:
    """Load the real N.I.N.A. Advanced Sequencer JSON template.

    This is intentionally based on a user-saved N.I.N.A. sequence scaffold instead
    of a hand-made XML placeholder.  N.I.N.A. keeps Advanced Sequencer structure,
    item types, parent refs, and trigger runners in this serialized JSON shape.
    """

    template_path = resolve_osc_template_path(path)
    return json.loads(template_path.read_text(encoding="utf-8-sig"))


def save_filled_sequence(
    path: str | Path,
    plan: NinaSequencePlan,
    *,
    template_path: str | Path | None = None,
) -> Path:
    """Fill the OSC template and write a N.I.N.A.-loadable sequence JSON file."""

    data = fill_osc_template(load_osc_template(template_path), plan)
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return out_path


def fill_osc_template(
    template: dict[str, Any], plan: NinaSequencePlan
) -> dict[str, Any]:
    data = copy.deepcopy(template)
    target_name = str(plan.target_name or "FZAstro Target").strip() or "FZAstro Target"
    root_id = str(data.get("$id") or "1")
    ra_values = parse_ra(plan.ra)
    dec_values = parse_dec(plan.dec)
    start_values = _time_values(plan.start_iso)
    end_values = _time_values(plan.end_iso)

    data["Name"] = f"FZAstro {target_name}"
    target = data.setdefault("Target", {})
    if isinstance(target, dict):
        target["TargetName"] = target_name
        target.setdefault("Rotation", 0.0)
        target["InputCoordinates"] = _coordinates_dict(ra_values, dec_values)

    _fill_nodes(
        data,
        root_id=root_id,
        target_name=target_name,
        ra_values=ra_values,
        dec_values=dec_values,
        start_values=start_values,
        end_values=end_values,
        exposure_seconds=int(plan.exposure_seconds),
        gain=int(plan.gain),
        frames=int(plan.frames),
        min_altitude_deg=float(plan.min_altitude_deg),
        note=str(plan.note or ""),
    )
    return data


def parse_ra(value: str) -> dict[str, float | int]:
    parts = _sexagesimal_parts(value)
    if not parts:
        return {"RAHours": 0, "RAMinutes": 0, "RASeconds": 0.0}
    hours = int(max(0, min(23, abs(parts[0]))))
    minutes = int(max(0, min(59, abs(parts[1] if len(parts) > 1 else 0))))
    seconds = float(max(0.0, min(59.999, abs(parts[2] if len(parts) > 2 else 0.0))))
    return {"RAHours": hours, "RAMinutes": minutes, "RASeconds": round(seconds, 3)}


def parse_dec(value: str) -> dict[str, float | int]:
    text = str(value or "").strip()
    sign = -1 if text.startswith("-") else 1
    parts = _sexagesimal_parts(text)
    if not parts:
        return {"DecDegrees": 0, "DecMinutes": 0, "DecSeconds": 0.0}
    degrees_abs = int(max(0, min(90, abs(parts[0]))))
    minutes = int(max(0, min(59, abs(parts[1] if len(parts) > 1 else 0))))
    seconds = float(max(0.0, min(59.999, abs(parts[2] if len(parts) > 2 else 0.0))))
    return {
        "DecDegrees": sign * degrees_abs,
        "DecMinutes": minutes,
        "DecSeconds": round(seconds, 3),
    }


def _sexagesimal_parts(value: str) -> list[float]:
    text = str(value or "").strip()
    if not text:
        return []
    text = text.replace("−", "-")
    text = re.sub(r"[hHdD°ºmM'′]", " ", text)
    text = re.sub(r"[sS\"”″]", " ", text)
    text = text.replace(":", " ")
    return [float(part) for part in re.findall(r"[+-]?\d+(?:\.\d+)?", text)[:3]]


def _time_values(value: str) -> dict[str, int]:
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except Exception:
        parsed = datetime.now()
    return {
        "Hours": int(parsed.hour),
        "Minutes": int(parsed.minute),
        "Seconds": int(parsed.second),
    }


def _coordinates_dict(
    ra_values: dict[str, float | int], dec_values: dict[str, float | int]
) -> dict[str, Any]:
    return {
        "$type": "NINA.Astrometry.InputCoordinates, NINA.Astrometry",
        **ra_values,
        **dec_values,
    }


def _is_type(node: dict[str, Any], type_name: str) -> bool:
    return type_name in str(node.get("$type") or "")


def _parent_ref(node: dict[str, Any]) -> str:
    parent = node.get("Parent")
    if isinstance(parent, dict):
        return str(parent.get("$ref") or "")
    return ""


def _fill_nodes(
    node: Any,
    *,
    root_id: str,
    target_name: str,
    ra_values: dict[str, float | int],
    dec_values: dict[str, float | int],
    start_values: dict[str, int],
    end_values: dict[str, int],
    exposure_seconds: int,
    gain: int,
    frames: int,
    min_altitude_deg: float,
    note: str,
) -> None:
    if isinstance(node, dict):
        if _is_type(node, "InputCoordinates"):
            node.update(ra_values)
            node.update(dec_values)

        if _is_type(node, "WaitForTime") and _parent_ref(node) == root_id:
            node.update(start_values)
            node["MinutesOffset"] = 0

        if _is_type(node, "TimeCondition"):
            node.update(end_values)
            node["MinutesOffset"] = 0

        if _is_type(node, "WaitUntilAboveHorizon") or _is_type(
            node, "AboveHorizonCondition"
        ):
            node["AltitudeOffset"] = float(min_altitude_deg)
            node["HasDsoParent"] = True

        if _is_type(node, "Platesolving.Center"):
            node["Inherited"] = True

        if _is_type(node, "TakeExposure"):
            node["ExposureTime"] = float(exposure_seconds)
            node["Gain"] = int(gain)
            node["ExposureCount"] = int(frames)
            node.setdefault("ImageType", "LIGHT")

        if _is_type(node, "CenterAfterDriftTrigger"):
            node["DistanceArcMinutes"] = float(node.get("DistanceArcMinutes") or 3.0)

        if _is_type(node, "Annotation"):
            text = str(node.get("Text") or "")
            if text.startswith("VERSION:"):
                node["Text"] = (
                    f"FZAstro generated plan for {target_name} · "
                    f"{exposure_seconds}s gain {gain} · {frames} frames. {note}"
                )

        for value in list(node.values()):
            _fill_nodes(
                value,
                root_id=root_id,
                target_name=target_name,
                ra_values=ra_values,
                dec_values=dec_values,
                start_values=start_values,
                end_values=end_values,
                exposure_seconds=exposure_seconds,
                gain=gain,
                frames=frames,
                min_altitude_deg=min_altitude_deg,
                note=note,
            )
    elif isinstance(node, list):
        for item in node:
            _fill_nodes(
                item,
                root_id=root_id,
                target_name=target_name,
                ra_values=ra_values,
                dec_values=dec_values,
                start_values=start_values,
                end_values=end_values,
                exposure_seconds=exposure_seconds,
                gain=gain,
                frames=frames,
                min_altitude_deg=min_altitude_deg,
                note=note,
            )
