import json
import re
import time
from datetime import datetime, timezone

from .config import MARKET_JSON_MAX_BYTES
from .logging_utils import log_exception
from .network_utils import get_limited_json


def _stock_number(value):
    """Convert finance API numbers or formatted strings to float."""
    if isinstance(value, (int, float)):
        return float(value)

    clean = re.sub(r"[^0-9+\-.]", "", str(value or "").strip())

    if clean in {"", "+", "-", ".", "+.", "-."}:
        return None

    try:
        return float(clean)
    except (TypeError, ValueError):
        return None


def _stock_market_state(meta):
    raw_state = str(meta.get("marketState") or "").strip().upper()

    state_names = {
        "REGULAR": "Open",
        "PRE": "Pre-market",
        "PREPRE": "Pre-market",
        "POST": "After hours",
        "POSTPOST": "After hours",
        "CLOSED": "Closed",
    }

    if raw_state in state_names:
        return state_names[raw_state]

    current_time = time.time()
    periods = meta.get("currentTradingPeriod") or {}

    for key, label in (
        ("pre", "Pre-market"),
        ("regular", "Open"),
        ("post", "After hours"),
    ):
        period = periods.get(key) or {}
        start = _stock_number(period.get("start"))
        end = _stock_number(period.get("end"))

        if start is not None and end is not None and start <= current_time < end:
            return label

    return "Closed"


def _format_stock_epoch(value):
    timestamp = _stock_number(value)

    if timestamp is None:
        return "Unavailable"

    try:
        return datetime.fromtimestamp(timestamp, tz=timezone.utc).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        )
    except (OSError, OverflowError, ValueError):
        return "Unavailable"


def _format_stock_quote_markdown(
    ticker,
    company_name,
    price,
    currency,
    change,
    percentage_change,
    market_status,
    quote_timestamp,
    exchange,
    source_name,
    source_url,
    retrieved_at,
):
    """Serialize a structured quote for the dedicated market-card renderer."""
    payload = {
        "ticker": str(ticker or "").strip().upper(),
        "company_name": str(company_name or ticker or "Market quote").strip(),
        "price": _stock_number(price),
        "currency": str(currency or "USD").strip().upper(),
        "change": _stock_number(change),
        "percentage_change": _stock_number(percentage_change),
        "market_status": str(market_status or "Unavailable").strip(),
        "quote_timestamp": str(quote_timestamp or "Unavailable").strip(),
        "exchange": str(exchange or "Unavailable").strip(),
        "source_name": str(source_name or "Source").strip(),
        "source_url": str(source_url or "").strip(),
        "retrieved_at": str(retrieved_at or "Unavailable").strip(),
    }

    return "[STOCK_QUOTE]\n" + json.dumps(
        payload, ensure_ascii=False, separators=(",", ":")
    )


def parse_stock_quote_payload(text):
    clean_text = str(text or "").strip()

    if not clean_text.startswith("[STOCK_QUOTE]"):
        return None

    json_text = clean_text[len("[STOCK_QUOTE]") :].strip()

    if not json_text:
        return None

    try:
        payload = json.loads(json_text)
    except (TypeError, ValueError, json.JSONDecodeError):
        return None

    if not isinstance(payload, dict):
        return None

    ticker = str(payload.get("ticker") or "").strip().upper()

    if not ticker:
        return None

    payload["ticker"] = ticker
    return payload


SOURCE_TAG_LABELS = {
    "llm": "LLM",
    "web_search": "Web",
    "web_page": "Web page",
    "web_screenshot": "Screenshot",
    "web_image": "Web image",
    "web_news": "News",
    "market_data": "Market",
    "astro_api": "Astro API",
    "document_knowledge": "Docs",
    "persistent_memory": "Memory",
    "attachments": "Files",
    "vision": "Vision",
    "app": "App",
    "python_execution": "Python",
}

SOURCE_TAG_TOOLTIPS = {
    "llm": "Generated by the selected local model from its learned knowledge and supplied prompt context.",
    "web_search": "Uses internet search results supplied by the app.",
    "web_page": "Uses a specific webpage opened and extracted by Playwright.",
    "web_screenshot": "Uses a live webpage screenshot captured by Playwright.",
    "web_image": "Uses image search or images extracted from a webpage.",
    "web_news": "Uses current RSS/news results supplied by the app.",
    "market_data": "Uses a structured market quote fetched by the app.",
    "astro_api": "Uses migrated FZASTRO astronomy tools and external astronomy/weather APIs.",
    "document_knowledge": "Uses the local Document Knowledge Library.",
    "persistent_memory": "Uses relevant entries from local persistent memory.",
    "attachments": "Uses files or images attached in the current request.",
    "vision": "Uses an image-capable model to inspect visual attachments.",
    "app": "Created directly by the application without an LLM rewrite.",
    "python_execution": "Local Python subprocess execution triggered manually by the user.",
}

SOURCE_TAG_ORDER = [
    "llm",
    "app",
    "python_execution",
    "web_search",
    "web_page",
    "web_screenshot",
    "web_image",
    "web_news",
    "market_data",
    "astro_api",
    "document_knowledge",
    "persistent_memory",
    "attachments",
    "vision",
]


def normalize_response_source_tags(source_tags):
    """Return stable, user-facing provenance tags for a response."""
    if isinstance(source_tags, str):
        raw_tags = re.split(r"[,|;\s]+", source_tags)
    else:
        raw_tags = list(source_tags or [])

    aliases = {
        "model": "llm",
        "local_model": "llm",
        "llm_knowledge": "llm",
        "web": "web_search",
        "internet": "web_search",
        "search": "web_search",
        "rendered_page": "web_page",
        "browser": "web_page",
        "page": "web_page",
        "website_screenshot": "web_screenshot",
        "screenshot": "web_screenshot",
        "image_search": "web_image",
        "images": "web_image",
        "news": "web_news",
        "stock": "market_data",
        "quote": "market_data",
        "market": "market_data",
        "astro": "astro_api",
        "astronomy": "astro_api",
        "astro_api": "astro_api",
        "fzastro": "astro_api",
        "docs": "document_knowledge",
        "documents": "document_knowledge",
        "knowledge": "document_knowledge",
        "document_library": "document_knowledge",
        "memory": "persistent_memory",
        "persistent": "persistent_memory",
        "file": "attachments",
        "files": "attachments",
        "attachment": "attachments",
        "attachments": "attachments",
        "python": "python_execution",
        "python_runner": "python_execution",
        "code_execution": "python_execution",
        "python_execution": "python_execution",
    }

    selected = []

    for raw_tag in raw_tags:
        clean_tag = re.sub(r"[^a-z0-9_\-]+", "_", str(raw_tag or "").strip().casefold())
        clean_tag = clean_tag.strip("_-")

        if not clean_tag:
            continue

        clean_tag = aliases.get(clean_tag, clean_tag)

        if clean_tag not in SOURCE_TAG_LABELS:
            continue

        if clean_tag not in selected:
            selected.append(clean_tag)

    selected.sort(
        key=lambda tag: (
            SOURCE_TAG_ORDER.index(tag) if tag in SOURCE_TAG_ORDER else 999,
            tag,
        )
    )
    return selected


def infer_response_source_tags(
    text="", files=None, web_articles=None, news_sources=None
):
    """Best-effort provenance for old history items that predate source tags."""
    raw_text = str(text or "")
    clean_text = raw_text.casefold()
    file_paths = [str(file_path or "") for file_path in (files or [])]
    tags = []

    def add(tag):
        if tag not in tags:
            tags.append(tag)

    if parse_stock_quote_payload(raw_text) is not None:
        add("market_data")

    if web_articles:
        add("web_search")

    if news_sources:
        if (
            any(
                re.fullmatch(r"NEWS_\d+", str(source_id or "").strip().upper())
                for source_id in news_sources
            )
            or "daily news brief" in clean_text
        ):
            add("web_news")
        else:
            add("web_search")

    if "[news headlines]" in clean_text or "daily news brief" in clean_text:
        add("web_news")

    if "[web articles]" in clean_text or "[internet context]" in clean_text:
        add("web_search")

    if "[rendered page]" in clean_text or "rendered page extracted" in clean_text:
        add("web_page")

    if "[web screenshot]" in clean_text or "website screenshot captured" in clean_text:
        add("web_screenshot")

    if "[web image]" in clean_text or "web image retrieved" in clean_text:
        add("web_image")

    if (
        "document knowledge library" in clean_text
        or "application-supplied document knowledge" in clean_text
        or "[knowledge excerpt" in clean_text
        or "document text returned directly" in clean_text
    ):
        add("document_knowledge")

    if "application-supplied persistent memory" in clean_text:
        add("persistent_memory")

    for file_path in file_paths:
        path_key = file_path.replace("\\", "/").casefold()

        if "document_knowledge_assets" in path_key:
            add("document_knowledge")
        elif "fzastro_web_screenshots" in path_key:
            add("web_screenshot")
        elif "web_images" in path_key:
            add("web_image")
        elif path_key:
            add("attachments")

    if not tags:
        add("llm")

    return normalize_response_source_tags(tags)


def source_tags_tooltip(source_tags):
    tags = normalize_response_source_tags(source_tags)

    if not tags:
        return ""

    lines = ["Response provenance:"]

    for tag in tags:
        label = SOURCE_TAG_LABELS.get(tag, tag)
        detail = SOURCE_TAG_TOOLTIPS.get(tag, "")
        lines.append(f"• {label}: {detail}" if detail else f"• {label}")

    return "\n".join(lines)


def build_response_source_tags(
    llm=False,
    app=False,
    search_results="",
    knowledge_context="",
    memory_context="",
    user_files=None,
    assistant_files=None,
    vision=False,
):
    tags = []

    def add(tag):
        if tag and tag not in tags:
            tags.append(tag)

    if llm:
        add("llm")

    if app:
        add("app")

    results_text = str(search_results or "")

    if "[NEWS HEADLINES]" in results_text:
        add("web_news")
    elif "[WEB SCREENSHOT]" in results_text:
        add("web_screenshot")
    elif "[WEB IMAGE]" in results_text:
        add("web_image")
    elif "[RENDERED PAGE]" in results_text:
        add("web_page")
    elif "[WEB ARTICLES]" in results_text or "[INTERNET CONTEXT]" in results_text:
        add("web_search")

    if str(knowledge_context or "").strip():
        add("document_knowledge")

    if str(memory_context or "").strip():
        add("persistent_memory")

    for file_path in list(user_files or []) + list(assistant_files or []):
        path_key = str(file_path or "").replace("\\", "/").casefold()

        if not path_key:
            continue

        if "document_knowledge_assets" in path_key:
            add("document_knowledge")
        elif "fzastro_web_screenshots" in path_key:
            add("web_screenshot")
        elif "web_images" in path_key:
            add("web_image")
        else:
            add("attachments")

    if vision:
        add("vision")

    return normalize_response_source_tags(tags)


def stock_quote_plain_text(payload):
    if not isinstance(payload, dict):
        return ""

    ticker = str(payload.get("ticker") or "").strip().upper()
    company_name = str(payload.get("company_name") or ticker or "Market quote").strip()
    currency = str(payload.get("currency") or "USD").strip().upper()
    price = _stock_number(payload.get("price"))
    change = _stock_number(payload.get("change"))
    percentage_change = _stock_number(payload.get("percentage_change"))

    if price is None:
        price_text = "Unavailable"
    elif currency == "USD":
        price_text = f"${price:,.2f} USD"
    else:
        price_text = f"{price:,.2f} {currency}"

    change_text = "Unavailable" if change is None else f"{change:+,.2f} {currency}"
    percentage_text = (
        "Unavailable" if percentage_change is None else f"{percentage_change:+.2f}%"
    )

    lines = [
        f"{company_name} ({ticker})",
        f"Price: {price_text}",
        f"Daily change: {change_text}",
        f"Percentage change: {percentage_text}",
        f"Market status: {payload.get('market_status') or 'Unavailable'}",
        f"Quote timestamp: {payload.get('quote_timestamp') or 'Unavailable'}",
        f"Exchange: {payload.get('exchange') or 'Unavailable'}",
        f"Source: {payload.get('source_name') or 'Source'} {payload.get('source_url') or ''}".rstrip(),
        f"Retrieved: {payload.get('retrieved_at') or 'Unavailable'}",
    ]

    return "\n".join(lines)


def _fetch_yahoo_stock_quote(ticker):
    company_names = {
        "CRM": "Salesforce",
        "DBX": "Dropbox",
        "CL=F": "Crude Oil",
        "GC=F": "Gold",
    }

    api_url = f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}"
    payload = get_limited_json(
        api_url,
        params={
            "interval": "1m",
            "range": "1d",
            "includePrePost": "true",
            "events": "div,splits",
        },
        timeout=15,
        max_bytes=MARKET_JSON_MAX_BYTES,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/149.0.0.0 Safari/537.36"
            ),
            "Accept": "application/json,text/plain,*/*",
        },
    )
    chart = payload.get("chart") or {}

    if chart.get("error"):
        raise ValueError(str(chart["error"]))

    results = chart.get("result") or []

    if not results:
        raise ValueError("Yahoo Finance returned no quote data.")

    meta = results[0].get("meta") or {}
    market_status = _stock_market_state(meta)

    regular_price = _stock_number(meta.get("regularMarketPrice"))
    price = regular_price
    quote_time = meta.get("regularMarketTime")

    if market_status == "Pre-market":
        price = _stock_number(meta.get("preMarketPrice")) or regular_price
        quote_time = meta.get("preMarketTime") or quote_time
    elif market_status == "After hours":
        price = _stock_number(meta.get("postMarketPrice")) or regular_price
        quote_time = meta.get("postMarketTime") or quote_time

    previous_close = _stock_number(meta.get("previousClose")) or _stock_number(
        meta.get("chartPreviousClose")
    )

    change = None
    percentage_change = None

    if price is not None and previous_close not in (None, 0):
        change = price - previous_close
        percentage_change = change / previous_close * 100.0

    company_name = str(
        meta.get("longName") or meta.get("shortName") or ""
    ).strip() or company_names.get(ticker, ticker)

    exchange = str(
        meta.get("fullExchangeName") or meta.get("exchangeName") or ""
    ).strip()

    retrieved_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    return _format_stock_quote_markdown(
        ticker=ticker,
        company_name=company_name,
        price=price,
        currency=meta.get("currency") or "USD",
        change=change,
        percentage_change=percentage_change,
        market_status=market_status,
        quote_timestamp=_format_stock_epoch(quote_time),
        exchange=exchange,
        source_name="Yahoo Finance",
        source_url=f"https://finance.yahoo.com/quote/{ticker}",
        retrieved_at=retrieved_at,
    )


def _fetch_nasdaq_stock_quote(ticker):
    company_names = {"CRM": "Salesforce", "DBX": "Dropbox"}

    api_url = f"https://api.nasdaq.com/api/quote/{ticker}/info"
    payload = get_limited_json(
        api_url,
        params={"assetclass": "stocks"},
        timeout=15,
        max_bytes=MARKET_JSON_MAX_BYTES,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/149.0.0.0 Safari/537.36"
            ),
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "en-US,en;q=0.9",
            "Origin": "https://www.nasdaq.com",
            "Referer": f"https://www.nasdaq.com/market-activity/stocks/{ticker.lower()}",
        },
    )
    data = payload.get("data") or {}
    primary = data.get("primaryData") or {}

    price = _stock_number(primary.get("lastSalePrice"))

    if price is None:
        raise ValueError("Nasdaq returned no last-sale price.")

    change = _stock_number(primary.get("netChange"))
    percentage_change = _stock_number(primary.get("percentageChange"))

    company_name = str(data.get("companyName") or "").strip() or company_names.get(
        ticker, ticker
    )

    market_status = str(
        data.get("marketStatus") or primary.get("marketStatus") or "Unavailable"
    ).strip()

    quote_timestamp = str(
        primary.get("lastTradeTimestamp")
        or data.get("lastTradeTimestamp")
        or "Unavailable"
    ).strip()

    exchange = str(data.get("exchange") or data.get("exchangeName") or "Nasdaq").strip()

    retrieved_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    return _format_stock_quote_markdown(
        ticker=ticker,
        company_name=company_name,
        price=price,
        currency="USD",
        change=change,
        percentage_change=percentage_change,
        market_status=market_status,
        quote_timestamp=quote_timestamp,
        exchange=exchange,
        source_name="Nasdaq",
        source_url=f"https://www.nasdaq.com/market-activity/stocks/{ticker.lower()}",
        retrieved_at=retrieved_at,
    )


def perform_stock_quote(ticker):
    """Fetch a structured live market quote without LLM estimation."""
    clean_ticker = re.sub(r"[^A-Za-z0-9.=\-]", "", str(ticker or "")).upper()

    asset_names = {
        "CRM": "Salesforce",
        "DBX": "Dropbox",
        "CL=F": "Crude Oil",
        "GC=F": "Gold",
    }

    if clean_ticker not in asset_names:
        return "Market quote failed: unsupported symbol."

    # Nasdaq provides a useful independent fallback for US equities. Commodity
    # futures use Yahoo Finance's structured chart endpoint directly.
    if clean_ticker in {"CRM", "DBX"}:
        sources = (
            ("Yahoo Finance", _fetch_yahoo_stock_quote),
            ("Nasdaq", _fetch_nasdaq_stock_quote),
        )
    else:
        sources = (("Yahoo Finance", _fetch_yahoo_stock_quote),)

    errors = []

    for source_name, fetcher in sources:
        try:
            return fetcher(clean_ticker)
        except Exception as error:
            log_exception("perform_stock_quote line 2419", error)
            clean_error = re.sub(r"\s+", " ", str(error)).strip()
            errors.append(f"{source_name}: {clean_error[:240]}")

    details = "\n".join(f"- {item}" for item in errors)
    asset_name = asset_names[clean_ticker]

    return (
        f"## {asset_name} quote unavailable\n\n"
        "The direct quote service did not return usable data.\n\n"
        f"{details}"
    )
