"""Migrated FZASTRO object shortcut catalogs.

These values come from the original FZASTRO web/index.html dropdown menus.
They are used by the desktop ASTRO lookup dialog to fill the object query.
"""

from __future__ import annotations

ASTRO_CATALOG_ROWS = [
    [
        {
            "id": "planets",
            "label": "Planets/Sun",
            "placeholder": "Select a Planet/Sun",
            "items": [
                {"label": "Sun", "query": "Sun"},
                {"label": "Mercury", "query": "Mercury"},
                {"label": "Venus", "query": "Venus"},
                {"label": "Earth", "query": "Earth"},
                {"label": "Mars", "query": "Mars"},
                {"label": "Jupiter", "query": "Jupiter"},
                {"label": "Saturn", "query": "Saturn"},
                {"label": "Uranus", "query": "Uranus"},
                {"label": "Neptune", "query": "Neptune"},
                {"label": "Pluto", "query": "Pluto"},
            ],
        },
        {
            "id": "moons",
            "label": "Moons",
            "placeholder": "Select a Moon",
            "items": [
                {"label": "Earth · Moon", "query": "Moon"},
                {"label": "Mars · Phobos", "query": "Phobos"},
                {"label": "Mars · Deimos", "query": "Deimos"},
                {"label": "Jupiter · Io", "query": "Io"},
                {"label": "Jupiter · Europa", "query": "Europa"},
                {"label": "Jupiter · Ganymede", "query": "Ganymede"},
                {"label": "Jupiter · Callisto", "query": "Callisto"},
                {"label": "Jupiter · Amalthea", "query": "Amalthea"},
                {"label": "Jupiter · Himalia", "query": "Himalia"},
                {"label": "Saturn · Mimas", "query": "Mimas"},
                {"label": "Saturn · Enceladus", "query": "Enceladus"},
                {"label": "Saturn · Tethys", "query": "Tethys"},
                {"label": "Saturn · Dione", "query": "Dione"},
                {"label": "Saturn · Rhea", "query": "Rhea"},
                {"label": "Saturn · Titan", "query": "Titan"},
                {"label": "Saturn · Hyperion", "query": "Hyperion"},
                {"label": "Saturn · Iapetus", "query": "Iapetus"},
                {"label": "Saturn · Phoebe", "query": "Phoebe"},
                {"label": "Uranus · Miranda", "query": "Miranda"},
                {"label": "Uranus · Ariel", "query": "Ariel"},
                {"label": "Uranus · Umbriel", "query": "Umbriel"},
                {"label": "Uranus · Titania", "query": "Titania"},
                {"label": "Uranus · Oberon", "query": "Oberon"},
                {"label": "Neptune · Triton", "query": "Triton"},
                {"label": "Neptune · Proteus", "query": "Proteus"},
                {"label": "Neptune · Nereid", "query": "Nereid"},
                {"label": "Pluto (Dwarf Planet) · Charon", "query": "Charon"},
            ],
        },
        {
            "id": "comets",
            "label": "Comets",
            "placeholder": "Select a Comet",
            "items": [
                {
                    "label": "Interstellar visitors · 1I/ʻOumuamua",
                    "query": "1I/ʻOumuamua",
                },
                {"label": "Interstellar visitors · 2I/Borisov", "query": "2I/Borisov"},
                {"label": "Interstellar visitors · 3I/ATLAS", "query": "3I/ATLAS"},
                {
                    "label": "Interstellar visitors (candidates) · C/2007 W1",
                    "query": "C/2007 W1",
                },
                {
                    "label": "Interstellar visitors (candidates) · C/2018 V1",
                    "query": "C/2018 V1",
                },
                {
                    "label": "Interstellar visitors (candidates) · C/2019 O3",
                    "query": "C/2019 O3",
                },
                {
                    "label": "Interstellar visitors (candidates) · C/2020 U1",
                    "query": "C/2020 U1",
                },
                {
                    "label": "Interstellar visitors (candidates) · C/2022 E3",
                    "query": "C/2022 E3",
                },
                {
                    "label": "Long‐period comet · C/1577 V1 (Tycho’s Comet)",
                    "query": "C/1577 V1",
                },
                {
                    "label": "Long‐period comet · C/1680 V1 (Great Comet of 1680)",
                    "query": "C/1680 V1",
                },
                {
                    "label": "Long‐period comet · C/1811 F1 (Great Comet of 1811)",
                    "query": "C/1811 F1",
                },
                {
                    "label": "Long‐period comet · C/1843 D1 (Great March Comet)",
                    "query": "C/1843 D1",
                },
                {
                    "label": "Long‐period comet · C/1858 L1 (Donati)",
                    "query": "C/1858 L1",
                },
                {
                    "label": "Long‐period comet · C/1874 H1 (Coggia)",
                    "query": "C/1874 H1",
                },
                {
                    "label": "Long‐period comet · C/1901 G1 (Great Comet of 1901)",
                    "query": "C/1901 G1",
                },
                {
                    "label": "Long‐period comet · C/1910 A1 (Great January Comet)",
                    "query": "C/1910 A1",
                },
                {
                    "label": "Long‐period comet · C/1956 R1 (Arend–Roland)",
                    "query": "C/1956 R1",
                },
                {
                    "label": "Long‐period comet · C/1965 S1 (Ikeya–Seki)",
                    "query": "C/1965 S1",
                },
                {
                    "label": "Long‐period comet · C/1973 E1 (Kohoutek)",
                    "query": "C/1973 E1",
                },
                {"label": "Long‐period comet · C/1975 V1 (West)", "query": "C/1975 V1"},
                {
                    "label": "Long‐period comet · C/1995 O1 (Hale-Bopp)",
                    "query": "C/1995 O1",
                },
                {
                    "label": "Long‐period comet · C/1996 B2 (Hyakutake)",
                    "query": "C/1996 B2",
                },
                {
                    "label": "Long‐period comet · C/2006 P1 (McNaught)",
                    "query": "C/2006 P1",
                },
                {
                    "label": "Long‐period comet · C/2020 F3 (NEOWISE)",
                    "query": "C/2020 F3",
                },
                {
                    "label": "Long‐period comet · C/2025 A6 (Lemmon)",
                    "query": "C/2025 A6",
                },
                {"label": "Long‐period comet · C/2025 R2 (SWAN)", "query": "C/2025 R2"},
                {
                    "label": "Long‐period comet · C/2025 K1 (ATLAS)",
                    "query": "C/2025 K1",
                },
            ],
        },
        {
            "id": "spacecraft",
            "label": "Spacecraft",
            "placeholder": "Select a Spacecraft",
            "items": [
                {
                    "label": "Earth Orbiters & Telescopes · International Space Station",
                    "query": "ISS",
                },
                {
                    "label": "Earth Orbiters & Telescopes · Hubble Space Telescope",
                    "query": "Hubble",
                },
                {
                    "label": "Earth Orbiters & Telescopes · James Webb Space Telescope",
                    "query": "JWST",
                },
                {"label": "Earth Orbiters & Telescopes · SOHO", "query": "SOHO"},
                {
                    "label": "Earth Orbiters & Telescopes · Kepler Space Telescope",
                    "query": "Kepler",
                },
                {"label": "Earth Orbiters & Telescopes · TESS", "query": "TESS"},
                {"label": "Earth Orbiters & Telescopes · Gaia", "query": "Gaia"},
                {
                    "label": "Earth Orbiters & Telescopes · Chandra X-ray Observatory",
                    "query": "Chandra",
                },
                {"label": "Planetary Missions · Curiosity (MSL)", "query": "Curiosity"},
                {
                    "label": "Planetary Missions · Perseverance (Mars 2020)",
                    "query": "Perseverance",
                },
                {"label": "Planetary Missions · Ingenuity", "query": "Ingenuity"},
                {
                    "label": "Planetary Missions · Juno (Jupiter Orbiter)",
                    "query": "Juno",
                },
                {
                    "label": "Planetary Missions · Cassini (Saturn Orbiter)",
                    "query": "Cassini",
                },
                {
                    "label": "Solar & Deep Space Missions · Parker Solar Probe",
                    "query": "Parker Solar Probe",
                },
                {
                    "label": "Solar & Deep Space Missions · Solar Orbiter",
                    "query": "Solar Orbiter",
                },
                {
                    "label": "Solar & Deep Space Missions · Voyager 1",
                    "query": "Voyager 1",
                },
                {
                    "label": "Solar & Deep Space Missions · Voyager 2",
                    "query": "Voyager 2",
                },
                {
                    "label": "Solar & Deep Space Missions · New Horizons",
                    "query": "New Horizons",
                },
                {"label": "Solar & Deep Space Missions · Lucy", "query": "Lucy"},
                {"label": "Solar & Deep Space Missions · Psyche", "query": "Psyche"},
            ],
        },
    ],
    [
        {
            "id": "stars",
            "label": "Brightest Stars",
            "placeholder": "Select a Star",
            "items": [
                {"label": "Sirius", "query": "NAME Sirius"},
                {"label": "Canopus", "query": "NAME Canopus"},
                {"label": "Arcturus", "query": "NAME Arcturus"},
                {"label": "Alpha Centauri", "query": "Alpha Centauri"},
                {"label": "Vega", "query": "NAME Vega"},
                {"label": "Capella", "query": "NAME Capella"},
                {"label": "Rigel", "query": "NAME Rigel"},
                {"label": "Procyon", "query": "NAME Procyon"},
                {"label": "Achernar", "query": "NAME Achernar"},
                {"label": "Betelgeuse", "query": "NAME Betelgeuse"},
                {"label": "Hadar", "query": "NAME Hadar"},
                {"label": "Altair", "query": "NAME Altair"},
                {"label": "Acrux", "query": "NAME Acrux"},
                {"label": "Aldebaran", "query": "NAME Aldebaran"},
                {"label": "Antares", "query": "NAME Antares"},
                {"label": "Spica", "query": "NAME Spica"},
                {"label": "Pollux", "query": "NAME Pollux"},
                {"label": "Fomalhaut", "query": "NAME Fomalhaut"},
                {"label": "Deneb", "query": "NAME Deneb"},
                {"label": "Mimosa", "query": "NAME Mimosa"},
                {"label": "Regulus", "query": "NAME Regulus"},
                {"label": "Adhara", "query": "NAME Adhara"},
                {"label": "Shaula", "query": "NAME Shaula"},
                {"label": "Castor", "query": "NAME Castor"},
                {"label": "Gacrux", "query": "NAME Gacrux"},
                {"label": "Bellatrix", "query": "NAME Bellatrix"},
                {"label": "Elnath", "query": "NAME Elnath"},
                {"label": "Miaplacidus", "query": "NAME Miaplacidus"},
                {"label": "Alnilam", "query": "NAME Alnilam"},
                {"label": "Alnair", "query": "NAME Alnair"},
            ],
        },
        {
            "id": "nebulas",
            "label": "Famous Nebulae",
            "placeholder": "Select a Nebula",
            "items": [
                {"label": "Orion Nebula (M42 / NGC 1976)", "query": "M42"},
                {"label": "Lagoon Nebula (M8 / NGC 6523)", "query": "M8"},
                {"label": "Eagle Nebula (M16 / NGC 6611)", "query": "M16"},
                {"label": "Omega Nebula (M17 / NGC 6618)", "query": "M17"},
                {"label": "Trifid Nebula (M20 / NGC 6514)", "query": "M20"},
                {"label": "Dumbbell Nebula (M27 / NGC 6853)", "query": "M27"},
                {"label": "Ring Nebula (M57 / NGC 6720)", "query": "M57"},
                {"label": "Owl Nebula (M97 / NGC 3587)", "query": "M97"},
                {"label": "ρ Oph Cloud (IC 4604)", "query": "IC 4604"},
                {"label": "California Nebula (NGC 1499)", "query": "NGC 1499"},
                {"label": "Iris Nebula (NGC 7023)", "query": "NGC 7023"},
                {"label": "Horsehead Nebula (IC 434)", "query": "IC 434"},
                {"label": "Flaming Star Nebula (IC 405)", "query": "IC 405"},
                {"label": "Veil Nebula (Western, NGC 6960)", "query": "NGC 6960"},
                {"label": "Veil Nebula (Eastern, NGC 6992)", "query": "NGC 6992"},
                {"label": "North America Nebula (NGC 7000)", "query": "NGC 7000"},
                {"label": "Pelican Nebula (IC 5070)", "query": "IC 5070"},
                {"label": "Sadr Region (IC 1318)", "query": "IC 1318"},
                {"label": "Seagull Nebula (IC 2177)", "query": "IC 2177"},
                {"label": "Crescent Nebula (NGC 6888)", "query": "NGC 6888"},
                {"label": "Jellyfish Nebula (IC 443)", "query": "IC 443"},
                {"label": "Rosette Nebula (NGC 2237)", "query": "NGC 2237"},
                {"label": "Rosette Cluster (NGC 2244)", "query": "NGC 2244"},
                {"label": "Cat’s Paw Nebula (NGC 6334)", "query": "NGC 6334"},
                {"label": "Running Chicken Nebula (IC 2944)", "query": "IC 2944"},
                {"label": "Bubble Nebula (NGC 7635)", "query": "NGC 7635"},
                {"label": "Carina Nebula (NGC 3372)", "query": "NGC 3372"},
                {"label": "Lobster Nebula (NGC 6357)", "query": "NGC 6357"},
                {"label": "Pacman Nebula (NGC 281)", "query": "NGC 281"},
                {"label": "Tadpoles Nebula (IC 410)", "query": "IC 410"},
                {"label": "Elephant’s Trunk Nebula (IC 1396)", "query": "IC 1396"},
            ],
        },
        {
            "id": "messier",
            "label": "Messier Catalog (M1–M110)",
            "placeholder": "Select a Messier Object",
            "items": [
                {"label": "M1 – Crab Nebula", "query": "M1"},
                {"label": "M2 – Globular Cluster", "query": "M2"},
                {"label": "M3 – Globular Cluster", "query": "M3"},
                {"label": "M4 – Globular Cluster", "query": "M4"},
                {"label": "M5 – Globular Cluster", "query": "M5"},
                {"label": "M6 – Butterfly Cluster", "query": "M6"},
                {"label": "M7 – Ptolemy Cluster", "query": "M7"},
                {"label": "M8 – Lagoon Nebula", "query": "M8"},
                {"label": "M9 – Globular Cluster", "query": "M9"},
                {"label": "M10 – Globular Cluster", "query": "M10"},
                {"label": "M11 – Wild Duck Cluster", "query": "M11"},
                {"label": "M12 – Globular Cluster", "query": "M12"},
                {"label": "M13 – Hercules Cluster", "query": "M13"},
                {"label": "M14 – Globular Cluster", "query": "M14"},
                {"label": "M15 – Great Pegasus Cluster", "query": "M15"},
                {"label": "M16 – Eagle Nebula", "query": "M16"},
                {"label": "M17 – Omega Nebula", "query": "M17"},
                {"label": "M18 – Open Cluster", "query": "M18"},
                {"label": "M19 – Globular Cluster", "query": "M19"},
                {"label": "M20 – Trifid Nebula", "query": "M20"},
                {"label": "M21 – Open Cluster", "query": "M21"},
                {"label": "M22 – Sagittarius Cluster", "query": "M22"},
                {"label": "M23 – Open Cluster", "query": "M23"},
                {"label": "M24 – Sagittarius Star Cloud", "query": "M24"},
                {"label": "M25 – Open Cluster", "query": "M25"},
                {"label": "M26 – Open Cluster", "query": "M26"},
                {"label": "M27 – Dumbbell Nebula", "query": "M27"},
                {"label": "M28 – Globular Cluster", "query": "M28"},
                {"label": "M29 – Open Cluster", "query": "M29"},
                {"label": "M30 – Globular Cluster", "query": "M30"},
                {"label": "M31 – Andromeda Galaxy", "query": "M31"},
                {"label": "M32 – Dwarf Elliptical", "query": "M32"},
                {"label": "M33 – Triangulum Galaxy", "query": "M33"},
                {"label": "M34 – Open Cluster", "query": "M34"},
                {"label": "M35 – Open Cluster", "query": "M35"},
                {"label": "M36 – Pinwheel Cluster", "query": "M36"},
                {"label": "M37 – Salt and Pepper Cluster", "query": "M37"},
                {"label": "M38 – Starfish Cluster", "query": "M38"},
                {"label": "M39 – Open Cluster", "query": "M39"},
                {"label": "M40 – Winnecke 4", "query": "M40"},
                {"label": "M41 – Open Cluster", "query": "M41"},
                {"label": "M42 – Orion Nebula", "query": "M42"},
                {"label": "M43 – De Mairan’s Nebula", "query": "M43"},
                {"label": "M44 – Beehive Cluster", "query": "M44"},
                {"label": "M45 – Pleiades", "query": "M45"},
                {"label": "M46 – Open Cluster", "query": "M46"},
                {"label": "M47 – Open Cluster", "query": "M47"},
                {"label": "M48 – Open Cluster", "query": "M48"},
                {"label": "M49 – Elliptical Galaxy", "query": "M49"},
                {"label": "M50 – Open Cluster", "query": "M50"},
                {"label": "M51 – Whirlpool Galaxy", "query": "M51"},
                {"label": "M52 – Open Cluster", "query": "M52"},
                {"label": "M53 – Globular Cluster", "query": "M53"},
                {"label": "M54 – Globular Cluster", "query": "M54"},
                {"label": "M55 – Globular Cluster", "query": "M55"},
                {"label": "M56 – Globular Cluster", "query": "M56"},
                {"label": "M57 – Ring Nebula", "query": "M57"},
                {"label": "M58 – Barred Spiral Galaxy", "query": "M58"},
                {"label": "M59 – Elliptical Galaxy", "query": "M59"},
                {"label": "M60 – Elliptical Galaxy", "query": "M60"},
                {"label": "M61 – Barred Spiral Galaxy", "query": "M61"},
                {"label": "M62 – Globular Cluster", "query": "M62"},
                {"label": "M63 – Sunflower Galaxy", "query": "M63"},
                {"label": "M64 – Black Eye Galaxy", "query": "M64"},
                {"label": "M65 – Spiral Galaxy", "query": "M65"},
                {"label": "M66 – Spiral Galaxy", "query": "M66"},
                {"label": "M67 – Open Cluster", "query": "M67"},
                {"label": "M68 – Globular Cluster", "query": "M68"},
                {"label": "M69 – Globular Cluster", "query": "M69"},
                {"label": "M70 – Globular Cluster", "query": "M70"},
                {"label": "M71 – Globular Cluster", "query": "M71"},
                {"label": "M72 – Globular Cluster", "query": "M72"},
                {"label": "M73 – Asterism", "query": "M73"},
                {"label": "M74 – Phantom Galaxy", "query": "M74"},
                {"label": "M75 – Globular Cluster", "query": "M75"},
                {"label": "M76 – Little Dumbbell", "query": "M76"},
                {"label": "M77 – Barred Spiral Galaxy", "query": "M77"},
                {"label": "M78 – Reflection Nebula", "query": "M78"},
                {"label": "M79 – Globular Cluster", "query": "M79"},
                {"label": "M80 – Globular Cluster", "query": "M80"},
                {"label": "M81 – Bode’s Galaxy", "query": "M81"},
                {"label": "M82 – Cigar Galaxy", "query": "M 82"},
                {"label": "M83 – Southern Pinwheel", "query": "M83"},
                {"label": "M84 – Elliptical Galaxy", "query": "M84"},
                {"label": "M85 – Lenticular Galaxy", "query": "M85"},
                {"label": "M86 – Elliptical Galaxy", "query": "M86"},
                {"label": "M87 – Virgo A", "query": "M87"},
                {"label": "M88 – Spiral Galaxy", "query": "M88"},
                {"label": "M89 – Elliptical Galaxy", "query": "M89"},
                {"label": "M90 – Spiral Galaxy", "query": "M90"},
                {"label": "M91 – Barred Spiral Galaxy", "query": "M91"},
                {"label": "M92 – Globular Cluster", "query": "M92"},
                {"label": "M93 – Open Cluster", "query": "M93"},
                {"label": "M94 – Spiral Galaxy", "query": "M94"},
                {"label": "M95 – Barred Spiral Galaxy", "query": "M95"},
                {"label": "M96 – Spiral Galaxy", "query": "M96"},
                {"label": "M97 – Owl Nebula", "query": "M97"},
                {"label": "M98 – Spiral Galaxy", "query": "M98"},
                {"label": "M99 – Spiral Galaxy", "query": "M99"},
                {"label": "M100 – Spiral Galaxy", "query": "M100"},
                {"label": "M101 – Pinwheel Galaxy", "query": "M101"},
                {"label": "M102 – Spindle Galaxy", "query": "M102"},
                {"label": "M103 – Open Cluster", "query": "M103"},
                {"label": "M104 – Sombrero Galaxy", "query": "M104"},
                {"label": "M105 – Elliptical Galaxy", "query": "M105"},
                {"label": "M106 – Spiral Galaxy", "query": "M106"},
                {"label": "M107 – Globular Cluster", "query": "M107"},
                {"label": "M108 – Spiral Galaxy", "query": "M108"},
                {"label": "M109 – Barred Spiral Galaxy", "query": "M109"},
                {"label": "M110 – Dwarf Elliptical", "query": "M110"},
            ],
        },
        {
            "id": "virgosupercluster",
            "label": "Virgo Supercluster Members",
            "placeholder": "Select a Galaxy or Group",
            "items": [
                {
                    "label": "Virgo Cluster (Core) · M87 – Virgo A (NGC 4486)",
                    "query": "NGC 4486",
                },
                {"label": "Virgo Cluster (Core) · M49 (NGC 4472)", "query": "NGC 4472"},
                {"label": "Virgo Cluster (Core) · M58 (NGC 4579)", "query": "NGC 4579"},
                {"label": "Virgo Cluster (Core) · M59 (NGC 4621)", "query": "NGC 4621"},
                {"label": "Virgo Cluster (Core) · M60 (NGC 4649)", "query": "NGC 4649"},
                {"label": "Virgo Cluster (Core) · M61 (NGC 4303)", "query": "NGC 4303"},
                {"label": "Virgo Cluster (Core) · M84 (NGC 4374)", "query": "NGC 4374"},
                {"label": "Virgo Cluster (Core) · M86 (NGC 4406)", "query": "NGC 4406"},
                {"label": "Virgo Cluster (Core) · M89 (NGC 4552)", "query": "NGC 4552"},
                {"label": "Virgo Cluster (Core) · M90 (NGC 4569)", "query": "NGC 4569"},
                {"label": "Virgo Cluster (Core) · M85 (NGC 4382)", "query": "NGC 4382"},
                {
                    "label": "Virgo Cluster (Core) · M49 Subgroup (NGC 4472 group)",
                    "query": "NGC 4472 group",
                },
                {
                    "label": "Virgo Cluster (Core) · M60 Subgroup (NGC 4649 group)",
                    "query": "NGC 4649 group",
                },
                {
                    "label": "Virgo Cluster (Core) · IC 1101 (Abell 2029 central)",
                    "query": "IC 1101",
                },
                {"label": "Virgo Cluster (Core) · NGC 4639", "query": "NGC 4639"},
                {"label": "Virgo Cluster (Core) · NGC 4388", "query": "NGC 4388"},
                {"label": "Virgo Cluster (Core) · NGC 4429", "query": "NGC 4429"},
                {"label": "Virgo Cluster (Core) · NGC 4438", "query": "NGC 4438"},
                {
                    "label": "Local Sheet (Local Group Vicinity) · Milky Way",
                    "query": "M31",
                },
                {
                    "label": "Local Sheet (Local Group Vicinity) · Andromeda Galaxy (M31)",
                    "query": "NGC 224",
                },
                {
                    "label": "Local Sheet (Local Group Vicinity) · Triangulum Galaxy (M33)",
                    "query": "NGC 598",
                },
                {
                    "label": "Local Sheet (Local Group Vicinity) · M81 Galaxy (NGC 3031)",
                    "query": "NGC 3031",
                },
                {
                    "label": "Local Sheet (Local Group Vicinity) · Centaurus A (NGC 5128)",
                    "query": "NGC 5128",
                },
                {
                    "label": "Local Sheet (Local Group Vicinity) · M83 Galaxy (NGC 5236)",
                    "query": "NGC 5236",
                },
                {
                    "label": "Fornax–Eridanus Cloud · Fornax A (NGC 1316)",
                    "query": "NGC 1316",
                },
                {"label": "Fornax–Eridanus Cloud · NGC 1399", "query": "NGC 1399"},
                {"label": "Fornax–Eridanus Cloud · NGC 1404", "query": "NGC 1404"},
                {"label": "Fornax–Eridanus Cloud · NGC 1380", "query": "NGC 1380"},
                {"label": "Fornax–Eridanus Cloud · NGC 1365", "query": "NGC 1365"},
                {
                    "label": "Leo Cloud (Leo I and Leo II) · M66 (NGC 3627)",
                    "query": "NGC 3627",
                },
                {
                    "label": "Leo Cloud (Leo I and Leo II) · M65 (NGC 3623)",
                    "query": "NGC 3623",
                },
                {
                    "label": "Leo Cloud (Leo I and Leo II) · M95 (NGC 3351)",
                    "query": "NGC 3351",
                },
                {
                    "label": "Leo Cloud (Leo I and Leo II) · M96 (NGC 3368)",
                    "query": "NGC 3368",
                },
                {
                    "label": "Leo Cloud (Leo I and Leo II) · M105 (NGC 3379)",
                    "query": "NGC 3379",
                },
                {
                    "label": "Leo Cloud (Leo I and Leo II) · NGC 3384",
                    "query": "NGC 3384",
                },
                {"label": "Coma I Cloud · NGC 4278", "query": "NGC 4278"},
                {"label": "Coma I Cloud · NGC 4419", "query": "NGC 4419"},
                {"label": "Coma I Cloud · NGC 4565", "query": "NGC 4565"},
                {"label": "Coma I Cloud · NGC 4725", "query": "NGC 4725"},
                {"label": "Ursa Major Cloud · M81 (NGC 3031)", "query": "NGC 3031"},
                {"label": "Ursa Major Cloud · M82 (NGC 3034)", "query": "NGC 3034"},
                {"label": "Ursa Major Cloud · NGC 3077", "query": "NGC 3077"},
                {"label": "Ursa Major Cloud · NGC 2976", "query": "NGC 2976"},
                {"label": "Ursa Major Cloud · NGC 2403", "query": "NGC 2403"},
            ],
        },
    ],
    [
        {
            "id": "closest-stars",
            "label": "Closest Stars",
            "placeholder": "Select a Star",
            "items": [
                {"label": "Proxima Centauri", "query": "Proxima Cen"},
                {"label": "Alpha Centauri A", "query": "alf Cen A"},
                {"label": "Alpha Centauri B", "query": "alf Cen B"},
                {"label": "Barnard’s Star", "query": "Barnard's Star"},
                {"label": "Wolf 359", "query": "Wolf 359"},
                {"label": "Lalande 21185", "query": "Lalande 21185"},
                {"label": "Sirius A", "query": "Sirius A"},
                {"label": "Sirius B", "query": "Sirius B"},
                {"label": "BL Ceti", "query": "BL Cet"},
                {"label": "UV Ceti", "query": "UV Cet"},
                {"label": "Ross 154", "query": "Ross 154"},
                {"label": "Ross 248", "query": "Ross 248"},
                {"label": "Epsilon Eridani", "query": "eps Eri"},
                {"label": "Lacaille 9352", "query": "Lacaille 9352"},
                {"label": "Ross 128", "query": "Ross 128"},
                {"label": "61 Cygni A", "query": "61 Cyg A"},
                {"label": "61 Cygni B", "query": "61 Cyg B"},
                {"label": "Procyon A", "query": "Procyon A"},
                {"label": "Procyon B", "query": "Procyon B"},
                {"label": "Struve 2398 A", "query": "STF 2398 A"},
                {"label": "Struve 2398 B", "query": "STF 2398 B"},
                {"label": "Groombridge 34 A", "query": "Groombridge 34 A"},
                {"label": "Groombridge 34 B", "query": "Groombridge 34 B"},
                {"label": "GJ 15 A", "query": "GJ 15 A"},
                {"label": "GJ 15 B", "query": "GJ 15 B"},
                {"label": "Epsilon Indi A", "query": "eps Ind A"},
                {"label": "Epsilon Indi Ba", "query": "eps Ind Ba"},
                {"label": "Epsilon Indi Bb", "query": "eps Ind Bb"},
                {"label": "DX Cancri", "query": "DX Cnc"},
                {"label": "GJ 1061", "query": "GJ 1061"},
                {"label": "YZ Ceti", "query": "YZ Cet"},
                {"label": "Teegarden’s Star", "query": "Teegarden's star"},
                {"label": "Kapteyn’s Star", "query": "Kapteyn's star"},
                {"label": "AX Microscopii", "query": "AX Mic"},
                {"label": "UV Microscopii", "query": "UV Mic"},
                {"label": "GJ 1005 A", "query": "GJ 1005 A"},
                {"label": "GJ 1005 B", "query": "GJ 1005 B"},
                {"label": "Kruger 60 A", "query": "Kruger 60 A"},
                {"label": "Kruger 60 B", "query": "Kruger 60 B"},
                {"label": "Ross 614 A", "query": "Ross 614 A"},
                {"label": "Ross 614 B", "query": "Ross 614 B"},
                {"label": "Van Maanen’s Star", "query": "van Maanen 2"},
                {"label": "Wolf 424 A", "query": "Wolf 424 A"},
                {"label": "Wolf 424 B", "query": "Wolf 424 B"},
                {"label": "LHS 292", "query": "LHS 292"},
                {"label": "GJ 674", "query": "GJ 674"},
                {"label": "GJ 412 A", "query": "GJ 412 A"},
                {"label": "GJ 412 B", "query": "GJ 412 B"},
                {"label": "Wolf 1061", "query": "Wolf 1061"},
                {"label": "GJ 628", "query": "GJ 628"},
                {"label": "GJ 832", "query": "GJ 832"},
                {"label": "AD Leonis", "query": "AD Leo"},
                {"label": "GJ 682", "query": "GJ 682"},
                {"label": "GJ 445", "query": "GJ 445"},
                {"label": "GJ 570 A", "query": "GJ 570 A"},
                {"label": "GJ 570 B", "query": "GJ 570 B"},
                {"label": "GJ 570 C", "query": "GJ 570 C"},
                {"label": "GJ 205", "query": "GJ 205"},
                {"label": "GJ 251", "query": "GJ 251"},
                {"label": "LHS 1565", "query": "LHS 1565"},
                {"label": "GJ 229 A", "query": "GJ 229 A"},
                {"label": "GJ 229 B", "query": "GJ 229 B"},
                {"label": "GJ 526", "query": "GJ 526"},
                {"label": "GJ 1002", "query": "GJ 1002"},
                {"label": "GJ 752 A", "query": "GJ 752 A"},
                {"label": "GJ 752 B", "query": "GJ 752 B"},
                {"label": "GJ 644 A", "query": "GJ 644 A"},
                {"label": "GJ 644 B", "query": "GJ 644 B"},
                {"label": "GJ 644 C", "query": "GJ 644 C"},
                {"label": "Xi Bootis A", "query": "xi Boo A"},
                {"label": "Xi Bootis B", "query": "xi Boo B"},
                {"label": "GJ 625", "query": "GJ 625"},
                {"label": "GJ 408", "query": "GJ 408"},
                {"label": "LHS 2924", "query": "LHS 2924"},
                {"label": "GJ 1116 A", "query": "GJ 1116 A"},
                {"label": "GJ 1116 B", "query": "GJ 1116 B"},
                {"label": "LHS 3003", "query": "LHS 3003"},
                {"label": "GJ 402", "query": "GJ 402"},
                {"label": "GJ 393", "query": "GJ 393"},
                {"label": "LHS 2634", "query": "LHS 2634"},
                {"label": "GJ 83.1", "query": "GJ 83.1"},
                {"label": "GJ 667 A", "query": "GJ 667 A"},
                {"label": "GJ 667 B", "query": "GJ 667 B"},
                {"label": "GJ 667 C", "query": "GJ 667 C"},
                {"label": "GJ 473 A", "query": "GJ 473 A"},
                {"label": "GJ 473 B", "query": "GJ 473 B"},
                {"label": "GJ 206", "query": "GJ 206"},
                {"label": "GJ 234 A", "query": "GJ 234 A"},
                {"label": "GJ 234 B", "query": "GJ 234 B"},
                {"label": "GJ 809", "query": "GJ 809"},
                {"label": "GJ 1", "query": "GJ 1"},
                {"label": "GJ 411", "query": "GJ 411"},
                {"label": "GJ 273", "query": "GJ 273"},
                {"label": "GJ 338 A", "query": "GJ 338 A"},
                {"label": "GJ 338 B", "query": "GJ 338 B"},
                {"label": "LHS 1723", "query": "LHS 1723"},
                {"label": "Ross 625", "query": "Ross 625"},
                {"label": "Tau Ceti", "query": "tau Cet"},
            ],
        },
        {
            "id": "galaxies",
            "label": "Famous Galaxies",
            "placeholder": "Select a Galaxy",
            "items": [
                {"label": "Andromeda Galaxy (M31 / NGC 224)", "query": "M31"},
                {"label": "Triangulum Galaxy (M33 / NGC 598)", "query": "M33"},
                {"label": "Whirlpool Galaxy (M51 / NGC 5194)", "query": "M51"},
                {"label": "Bode’s Galaxy (M81 / NGC 3031)", "query": "M81"},
                {"label": "Cigar Galaxy (M82 / NGC 3034)", "query": "M82"},
                {"label": "Virgo A (M87 / NGC 4486)", "query": "M87"},
                {"label": "Pinwheel Galaxy (M101 / NGC 5457)", "query": "M101"},
                {"label": "Sculptor Galaxy (NGC 253)", "query": "NGC 253"},
                {"label": "Spiral Galaxy (NGC 300)", "query": "NGC 300"},
                {"label": "Edge-on Galaxy (NGC 891)", "query": "NGC 891"},
                {"label": "Barred Spiral Galaxy (NGC 1300)", "query": "NGC 1300"},
                {"label": "Great Barred Spiral (NGC 1365)", "query": "NGC 1365"},
                {"label": "Spiral Galaxy (NGC 2403)", "query": "NGC 2403"},
                {"label": "Barred Spiral Galaxy (NGC 2903)", "query": "NGC 2903"},
                {"label": "Spindle Galaxy (NGC 3115)", "query": "NGC 3115"},
                {"label": "Spiral Galaxy (NGC 3184)", "query": "NGC 3184"},
                {"label": "Flocculent Spiral (NGC 3521)", "query": "NGC 3521"},
                {
                    "label": "Hamburger Galaxy (NGC 3628, Leo Triplet)",
                    "query": "NGC 3628",
                },
                {"label": "Barred Spiral Galaxy (NGC 4236)", "query": "NGC 4236"},
                {"label": "Dwarf Seyfert (NGC 4395)", "query": "NGC 4395"},
                {"label": "Magellanic-type (NGC 4449)", "query": "NGC 4449"},
                {"label": "Cocoon Galaxy (NGC 4490)", "query": "NGC 4490"},
                {"label": "Lenticular Galaxy (NGC 4526)", "query": "NGC 4526"},
                {"label": "Spiral Galaxy (NGC 4559)", "query": "NGC 4559"},
                {"label": "Needle Galaxy (NGC 4565)", "query": "NGC 4565"},
                {"label": "Whale Galaxy (NGC 4631)", "query": "NGC 4631"},
                {"label": "Hockey Stick Galaxy (NGC 4656)", "query": "NGC 4656"},
                {"label": "Elliptical Galaxy (NGC 4697)", "query": "NGC 4697"},
                {"label": "One-armed Spiral (NGC 4725)", "query": "NGC 4725"},
                {"label": "Edge-on Spiral (NGC 4945)", "query": "NGC 4945"},
                {"label": "Centaurus A (NGC 5128)", "query": "NGC 5128"},
                {"label": "Milky Way Twin (NGC 6744)", "query": "NGC 6744"},
                {"label": "Fireworks Galaxy (NGC 6946)", "query": "NGC 6946"},
                {"label": "Starburst Dwarf (IC 10)", "query": "IC 10"},
                {"label": "Dwarf Irregular (IC 1613)", "query": "IC 1613"},
                {"label": "Coddington’s Nebula (IC 2574)", "query": "IC 2574"},
                {"label": "Hidden Galaxy (IC 342)", "query": "IC 342"},
            ],
        },
        {
            "id": "localgroup",
            "label": "Local Group Galaxies",
            "placeholder": "Select a Galaxy Member",
            "items": [
                {"label": "Milky Way Subgroup · Milky Way", "query": "M31"},
                {
                    "label": "Milky Way Subgroup · Large Magellanic Cloud",
                    "query": "PGC 17223",
                },
                {
                    "label": "Milky Way Subgroup · Small Magellanic Cloud",
                    "query": "PGC 3085",
                },
                {
                    "label": "Milky Way Subgroup · Sagittarius Dwarf Spheroidal",
                    "query": "PGC 6240",
                },
                {
                    "label": "Milky Way Subgroup · Ursa Minor Dwarf",
                    "query": "PGC 54074",
                },
                {"label": "Milky Way Subgroup · Draco Dwarf", "query": "PGC 5918"},
                {"label": "Milky Way Subgroup · Carina Dwarf", "query": "PGC 19441"},
                {"label": "Milky Way Subgroup · Sextans Dwarf", "query": "PGC 49418"},
                {"label": "Milky Way Subgroup · Sculptor Dwarf", "query": "PGC 3589"},
                {"label": "Milky Way Subgroup · Fornax Dwarf", "query": "PGC 10074"},
                {"label": "Milky Way Subgroup · Leo I Dwarf", "query": "PGC 29488"},
                {"label": "Milky Way Subgroup · Leo II Dwarf", "query": "PGC 34176"},
                {
                    "label": "Milky Way Subgroup · Canes Venatici I Dwarf",
                    "query": "PGC 46522",
                },
                {
                    "label": "Milky Way Subgroup · Canes Venatici II Dwarf",
                    "query": "PGC 46892",
                },
                {
                    "label": "Milky Way Subgroup · Bootes I Dwarf",
                    "query": "PGC 4713553",
                },
                {
                    "label": "Milky Way Subgroup · Bootes II Dwarf",
                    "query": "PGC 4713554",
                },
                {
                    "label": "Milky Way Subgroup · Hercules Dwarf",
                    "query": "PGC 4713555",
                },
                {
                    "label": "Milky Way Subgroup · Ursa Major I Dwarf",
                    "query": "PGC 4713556",
                },
                {
                    "label": "Milky Way Subgroup · Ursa Major II Dwarf",
                    "query": "PGC 4713557",
                },
                {"label": "Milky Way Subgroup · Segue 1 Dwarf", "query": "PGC 4713558"},
                {"label": "Milky Way Subgroup · Segue 2 Dwarf", "query": "PGC 4713559"},
                {
                    "label": "Milky Way Subgroup · Reticulum II Dwarf",
                    "query": "PGC 4713560",
                },
                {
                    "label": "Milky Way Subgroup · Tucana III Dwarf",
                    "query": "PGC 4713561",
                },
                {
                    "label": "Milky Way Subgroup · Crater II Dwarf",
                    "query": "PGC 4713562",
                },
                {
                    "label": "Milky Way Subgroup · Antlia 2 Dwarf",
                    "query": "PGC 4713563",
                },
                {
                    "label": "Andromeda Subgroup · Andromeda Galaxy (M31)",
                    "query": "NGC 224",
                },
                {
                    "label": "Andromeda Subgroup · Triangulum Galaxy (M33)",
                    "query": "NGC 598",
                },
                {"label": "Andromeda Subgroup · M32", "query": "NGC 221"},
                {"label": "Andromeda Subgroup · M110", "query": "NGC 205"},
                {"label": "Andromeda Subgroup · NGC 147", "query": "NGC 147"},
                {"label": "Andromeda Subgroup · NGC 185", "query": "NGC 185"},
                {"label": "Andromeda Subgroup · Andromeda I", "query": "PGC 2807158"},
                {"label": "Andromeda Subgroup · Andromeda II", "query": "PGC 2173665"},
                {"label": "Andromeda Subgroup · Andromeda III", "query": "PGC 2807159"},
                {"label": "Andromeda Subgroup · Andromeda IV", "query": "PGC 2173826"},
                {"label": "Andromeda Subgroup · Andromeda V", "query": "PGC 2807161"},
                {
                    "label": "Andromeda Subgroup · Andromeda VI (Peg dSph)",
                    "query": "PGC 2173663",
                },
                {
                    "label": "Andromeda Subgroup · Andromeda VII (Cas dSph)",
                    "query": "PGC 2173673",
                },
                {
                    "label": "Andromeda Subgroup · Andromeda VIII",
                    "query": "PGC 4713570",
                },
                {"label": "Andromeda Subgroup · Andromeda IX", "query": "PGC 4713571"},
                {"label": "M33 Subgroup · Triangulum Galaxy (M33)", "query": "NGC 598"},
                {"label": "M33 Subgroup · Pisces Dwarf", "query": "PGC 3792"},
                {"label": "M33 Subgroup · Andromeda XXII", "query": "PGC 4713578"},
                {"label": "Independent Members · IC 10", "query": "IC 10"},
                {"label": "Independent Members · IC 1613", "query": "IC 1613"},
                {"label": "Independent Members · WLM Galaxy", "query": "PGC 143"},
                {"label": "Independent Members · Leo A", "query": "PGC 28868"},
                {"label": "Independent Members · Leo T", "query": "PGC 4713544"},
                {"label": "Independent Members · Phoenix Dwarf", "query": "PGC 6830"},
                {
                    "label": "Independent Members · Pegasus Dwarf Irregular",
                    "query": "PGC 69256",
                },
                {
                    "label": "Independent Members · Sagittarius Dwarf Irregular (SagDIG)",
                    "query": "PGC 63287",
                },
                {"label": "Independent Members · Cetus Dwarf", "query": "PGC 47448"},
                {"label": "Independent Members · Tucana Dwarf", "query": "PGC 69519"},
                {"label": "Independent Members · Aquarius Dwarf", "query": "PGC 65367"},
            ],
        },
        {
            "id": "localsc",
            "label": "Local Superclusters",
            "placeholder": "Select a Supercluster",
            "items": [
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Laniakea Supercluster",
                    "query": "NAME Laniakea Supercluster",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Virgo Supercluster",
                    "query": "NAME Virgo Supercluster",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Centaurus Cluster",
                    "query": "Abell 3526",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Hydra Cluster",
                    "query": "Abell 1060",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Norma Cluster",
                    "query": "Abell 3627",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Pavo–Indus Supercluster",
                    "query": "NAME Pavo-Indus Supercluster",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Antlia Wall",
                    "query": "NAME Antlia Wall",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Local Sheet / Local Group",
                    "query": "NAME Local Sheet",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Sculptor Group",
                    "query": "NAME Sculptor Group",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Centaurus A / M83 Group",
                    "query": "NAME Centaurus A Group",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Leo Cloud",
                    "query": "NAME Leo Cloud",
                },
                {
                    "label": "Laniakea Supercluster (Home Supercluster) · Fornax–Eridanus Cloud",
                    "query": "NAME Fornax-Eridanus Cloud",
                },
                {
                    "label": "Perseus–Pisces Supercluster",
                    "query": "NAME Perseus-Pisces Supercluster",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Perseus Cluster",
                    "query": "Abell 426",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Pisces Cluster",
                    "query": "Abell 262",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Abell 347 Cluster",
                    "query": "Abell 347",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Triangulum Cluster",
                    "query": "NAME Triangulum Cluster",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Pegasus Cluster",
                    "query": "NAME Pegasus Cluster",
                },
                {
                    "label": "Perseus–Pisces Supercluster · NGC 383 Group",
                    "query": "NAME NGC 383 Group",
                },
                {
                    "label": "Perseus–Pisces Supercluster · Lacerta Cloud",
                    "query": "NAME Lacerta Cloud",
                },
                {"label": "Coma Supercluster", "query": "NAME Coma Supercluster"},
                {"label": "Coma Supercluster · Coma Cluster", "query": "Abell 1656"},
                {"label": "Coma Supercluster · Leo Cluster", "query": "Abell 1367"},
                {
                    "label": "Coma Supercluster · Abell 2199 Cluster",
                    "query": "Abell 2199",
                },
                {
                    "label": "Coma Supercluster · Abell 2197 Cluster",
                    "query": "Abell 2197",
                },
                {
                    "label": "Coma Supercluster · Canes Venatici Cloud",
                    "query": "NAME Canes Venatici Cloud",
                },
                {
                    "label": "Coma Supercluster · Bootes Cloud",
                    "query": "NAME Bootes Cloud",
                },
                {
                    "label": "Hercules Supercluster",
                    "query": "NAME Hercules Supercluster",
                },
                {
                    "label": "Hercules Supercluster · Hercules Cluster",
                    "query": "Abell 2151",
                },
                {
                    "label": "Hercules Supercluster · Abell 2147 Cluster",
                    "query": "Abell 2147",
                },
                {
                    "label": "Hercules Supercluster · Abell 2152 Cluster",
                    "query": "Abell 2152",
                },
                {
                    "label": "Hercules Supercluster · Hercules–Corona Borealis Great Wall",
                    "query": "NAME Hercules-Corona Borealis Great Wall",
                },
                {"label": "Shapley Supercluster", "query": "NAME Shapley Supercluster"},
                {
                    "label": "Shapley Supercluster · Abell 3558 Cluster",
                    "query": "Abell 3558",
                },
                {
                    "label": "Shapley Supercluster · Abell 3565 Cluster",
                    "query": "Abell 3565",
                },
                {
                    "label": "Shapley Supercluster · Abell 3571 Cluster",
                    "query": "Abell 3571",
                },
                {
                    "label": "Shapley Supercluster · Abell 3528 Cluster",
                    "query": "Abell 3528",
                },
                {
                    "label": "Shapley Supercluster · Abell 3532 Cluster",
                    "query": "Abell 3532",
                },
                {
                    "label": "Shapley Supercluster · Norma–Shapley Filament",
                    "query": "NAME Norma-Shapley Filament",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Great Attractor",
                    "query": "NAME Great Attractor",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Norma Cluster (Abell 3627)",
                    "query": "Abell 3627",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Abell 3565 Cluster",
                    "query": "Abell 3565",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Centaurus Cluster (Abell 3526)",
                    "query": "Abell 3526",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Hydra Cluster (Abell 1060)",
                    "query": "Abell 1060",
                },
                {
                    "label": "Hydra–Centaurus / Great Attractor Region · Pavo–Indus Filament",
                    "query": "NAME Pavo-Indus Filament",
                },
                {
                    "label": "Pisces–Cetus Supercluster Complex",
                    "query": "NAME Pisces-Cetus Supercluster Complex",
                },
                {
                    "label": "Pisces–Cetus Supercluster Complex · Pisces–Cetus Filament",
                    "query": "NAME Pisces-Cetus Filament",
                },
                {
                    "label": "Pisces–Cetus Supercluster Complex · Cetus Cluster",
                    "query": "NAME Cetus Cluster",
                },
                {
                    "label": "Pisces–Cetus Supercluster Complex · Pisces Cluster",
                    "query": "NAME Pisces Cluster",
                },
                {
                    "label": "Pisces–Cetus Supercluster Complex · Sculptor Filament",
                    "query": "NAME Sculptor Filament",
                },
            ],
        },
    ],
]
